name: youtube_downloader
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  cross_file: ^0.3.3+2
  cupertino_icons: ^1.0.2
  device_info_plus: ^8.0.0
  extended_image: ^6.3.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  flutter_timezone: ^1.0.4
  get: 4.6.5
  path: ^1.8.2
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  velocity_x: ^3.6.0
  youtube_explode_dart: ^1.12.3

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/.
    - sound/
